easy_admin:
    entities:
        - App\Entity\User
        - App\Entity\Member
        - App\Entity\News
        - App\Entity\NflTeam
        - App\Entity\Score
        - App\Entity\Season
        - App\Entity\UserGroup
        - App\Entity\Article
        - App\Entity\Category
